apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-config
  namespace: adguard
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-work
  namespace: adguard
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
